name: Update AL-Go system files

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read AL-Go settings
        uses: microsoft/AL-Go-Actions/ReadSettings@main
        with:
          shell: powershell

      - name: Check for updates to AL-Go system files
        uses: microsoft/AL-Go-Actions/CheckForUpdates@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          shell: powershell
          downloadLatest: true
