name: Validate AL Extension

on:
  workflow_dispatch:

jobs:
  validate:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install BcContainerHelper
        shell: pwsh
        run: Install-Module BcContainerHelper -Force -Scope CurrentUser

      - name: Build the .app package
        shell: pwsh
        run: |

          # Load credentials
          $username = "${{ secrets.BC_USERNAME }}"
          $passwordPlain = "${{ secrets.BC_PASSWORD }}"

          if (-not $username -or -not $passwordPlain) {
            throw "BC_USERNAME or BC_PASSWORD is empty — Check your GitHub Secrets."
          }

          $securePass = ConvertTo-SecureString $passwordPlain -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential($username, $securePass)

          New-BcContainer -accept_eula `
            -accept_outdated `
            -containerName "buildcontainer" `
            -imageName "mcr.microsoft.com/businesscentral/sandbox:ltsc2022" `
            -auth NavUserPassword `
            -credential $credential `
            -updateHosts `
            -doNotExportObjectsToText

          Compile-AppInBCContainer `
            -containerName buildcontainer `
            -appProjectFolder "$PWD/app" `
            -appOutputFolder "$PWD/output"

      - name: Run AL Validation
        shell: pwsh
        run: |
          Run-AlValidation `
            -apps @("app/*.app") `
            -validateCurrent `
            -countries @("gb","w1") `
            -affixes @("hot") `
            -supportedCountries @("gb","w1")